"""
Django settings for social_media_content_manager project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Add at the bottom of settings.py

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-!#lr&be)uqcl&im_0^d_s2i6yxnc$d!on^y9)e*64_swlto0__"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "content",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "social_media_content_manager.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "social_media_content_manager.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
SESSION_ENGINE = 'django.contrib.sessions.backends.file'
SESSION_FILE_PATH = BASE_DIR / 'sessions'

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
os.makedirs(MEDIA_ROOT, exist_ok=True)
os.makedirs(STATICFILES_DIRS[0], exist_ok=True)
os.makedirs(SESSION_FILE_PATH, exist_ok=True)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

# settings.py - MINIMAL CONFIGURATION (ALL YOU NEED)

# Gemini API (REQUIRED)
GEMINI_API_KEY = 'key'
GEMINI_MODEL = "flash"  
GEMINI_TIMEOUT_SECONDS = 60
GEMINI_MAX_OUTPUT_TOKENS = 4096
GEMINI_TEMPERATURE = 1.0  # Note: Gemma 4 performs best at 1.0


# Whisper Model (for video transcription)
WHISPER_MODEL_NAME = "base"

# YouTube API (Optional - for real trends)
YOUTUBE_API_KEY = 'YOUR_YOUTUBE_API_KEY_HERE'  # Get from Google Cloud Console

# ============================================================
# FEATURE FLAGS (Control which services are enabled)
# ============================================================

ENABLE_OPENCV_ANALYSIS = True  # Image/video analysis
ENABLE_DUCKDUCKGO_TRENDS = False  # DuckDuckGo (often rate limited)
ENABLE_YOUTUBE_API = True  # YouTube API for trends (requires API key)
ENABLE_AUTO_TRENDING = True  # Auto trend detection
ENABLE_GEMINI_FALLBACK = True  # Use mock responses if Gemini fails
ENABLE_AUDIO_TRANSCRIPTION = True  # Audio transcription for videos

# ============================================================
# PROCESSING LIMITS
# ============================================================

AI_MAX_TEXT_CHARS = 6000
AI_FFMPEG_TIMEOUT_SECONDS = 140
AI_CACHE_TTL_SECONDS = 3600
AI_JOB_TTL_SECONDS = 86400
AI_RATE_LIMIT = 50
AI_RATE_WINDOW_SECONDS = 3600


# YOUTUBE_API_KEY = None  # Leave commented out
os.environ['KMP_DUPLICATE_LIB_OK'] = 'TRUE'